import Header from "@/components/Header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-slate-500 font-sans flex flex-col min-h-screen ">
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
